let heroes = [
    {
        nom: "Thrall",
        image: "./img/warcraft/thrall.png",
        univers: "Warcraft",
        roles : "Guerrier",
    },
    {
        nom: "Sonya",
        image: "./img/diablo/sonya.png",
        univers: "Diablo",
        roles : "Guerrier",
    },
    {
        nom: "Deckard",
        image: "./img/diablo/deckard.png",
        univers: "Diablo",
        roles : "Healer",
    },
    {
        nom: "Artanis",
        image: "./img/starcraft/artanis.png",
        univers: "Starcraft",
        roles : "Guerrier",
    },
    {
        nom: "Chen",
        image: "./img/warcraft/chen.png",
        univers: "Warcraft",
        roles : "Tank",
    },
    {
        nom: "Ana",
        image: "./img/overwatch/ana.png",
        univers: "Overwatch",
        roles : "Healer",
    },
    {
        nom: "Vikings",
        image: "./img/nexus/the-lost-vikings.png",
        univers: "Nexus",
        roles : "Soutien",
    },
    {
        nom: "Orphea",
        image: "./img/nexus/orphea.png",
        univers: "Nexus",
        roles : "Distance",
    },
    {
        nom: "Qhira",
        image: "./img/nexus/qhira.png",
        univers: "Nexus",
        roles : "Assassin",
    },
    {
        nom: "D.V.A",
        image: "./img/overwatch/dva.png",
        univers: "Overwatch",
        roles : "Guerrier",
    },
    {
        nom: "Genji",
        image: "./img/overwatch/genji.png",
        univers: "Overwatch",
        roles : "Distance",
    },
    {
        nom: "Hanzo",
        image: "./img/overwatch/hanzo.png",
        univers: "Overwatch",
        roles : "Distance",
    },
    {
        nom: "Chacal",
        image: "./img/overwatch/junkrat.png",
        univers: "Overwatch",
        roles : "Distance",
    },
    {
        nom: "Lucio",
        image: "./img/overwatch/lucio.png",
        univers: "Overwatch",
        roles : "Healer",
    },
    {
        nom: "Mei",
        image: "./img/overwatch/mei.png",
        univers: "Overwatch",
        roles : "Tank",
    },
    {
        nom: "Tracer",
        image: "./img/overwatch/tracer.png",
        univers: "Overwatch",
        roles : "Distance",
    },
    {
        nom: "Zarya",
        image: "./img/overwatch/zarya.png",
        univers: "Overwatch",
        roles : "Soutien",
    },
    {
        nom: "Auriel",
        image: "./img/diablo/auriel.png",
        univers: "Diablo",
        roles : "Healer",
    },
    {
        nom: "Azmodan",
        image: "./img/diablo/azmodan.png",
        univers: "Diablo",
        roles : "Distance",
    },
    {
        nom: "Cassia",
        image: "./img/diablo/cassia.png",
        univers: "Diablo",
        roles : "Distance",
    },
    {
        nom: "Diablo",
        image: "./img/diablo/diablo.png",
        univers: "Diablo",
        roles : "Tank",
    },
    {
        nom: "Imperius",
        image: "./img/diablo/imperius.png",
        univers: "Diablo",
        roles : "Guerrier",
    },
    {
        nom: "Johanna",
        image: "./img/diablo/johanna.png",
        univers: "Diablo",
        roles : "Tank",
    },
    {
        nom: "Kharazim",
        image: "./img/diablo/kharazim.png",
        univers: "Diablo",
        roles : "Healer",
    },
    {
        nom: "Leoric",
        image: "./img/diablo/leoric.png",
        univers: "Diablo",
        roles : "Guerrier",
    },{
        nom: "Li-Ming",
        image: "./img/diablo/li-ming.png",
        univers: "Diablo",
        roles : "Distance",
    },
    {
        nom: "Malthael",
        image: "./img/diablo/malthael.png",
        univers: "Diablo",
        roles : "Guerrier",
    },
    {
        nom: "Mephisto",
        image: "./img/diablo/mephisto.png",
        univers: "Diablo",
        roles : "Distance",
    },
    {
        nom: "Nazeebo",
        image: "./img/diablo/nazeebo.png",
        univers: "Diablo",
        roles : "Distance",
    },
    {
        nom: "Le Boucher",
        image: "./img/diablo/the-butcher.png",
        univers: "Diablo",
        roles : "Assassin",
    },
    {
        nom: "Tyrael",
        image: "./img/diablo/tyrael.png",
        univers: "Diablo",
        roles : "Tank",
    },
    {
        nom: "Valla",
        image: "./img/diablo/valla.png",
        univers: "Diablo",
        roles : "Distance",
    },
    {
        nom: "Xul",
        image: "./img/diablo/xul.png",
        univers: "Diablo",
        roles : "Guerrier",
    },
]
/*
    {
        nom: "",
        image: "./",
        univers: "",
        roles : "",
    },
*/